
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
descmription: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Tracking will be disabled in development mode.
# To enable production mode set enviroment variable JEKYLL_ENV=production.
# Github pages automatically sets JEKYLL_ENV to production. For testing use
# $ JEKYLL_ENV=production jekyll serve
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-123-456          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - octopress-autoprefixer
  - jekyll-analytics
exclude:
  - Gemfile
  - Gemfile.lock
